const projects = [
  {
    slug: 'nova-salon',
    title: 'Nova Salon Luxury Beauty Studio & Booking Platform',
    category: 'Full-Stack Web',
    status: 'Live',
    featured: true,
    desc: 'A premium salon booking and management platform with a luxury client journey, live availability, and a full admin dashboard for operations and bookings.',
    long: `Nova Salon is a conversion-focused salon website and booking platform designed for a premium beauty brand. It combines a polished client-facing experience with a robust admin system for service management, appointment handling, analytics, and content updates. Built to feel premium and seamless while keeping booking flows efficient and operationally reliable.`,
    problem: 'Luxury beauty brands need a polished online presence and a frictionless booking experience without sacrificing operational control behind the scenes.',
    solution: 'Built a full-stack Next.js platform featuring a guided appointment flow, live slot availability checks, secure admin tooling, automated confirmations, and a premium brand-led design system.',
    outcomes: [
      'End-to-end salon booking flow with real-time slot validation',
      'Admin dashboard for bookings, analytics, service management, and CMS updates',
      'Automated email and WhatsApp confirmations for client bookings',
      'Luxury brand experience optimized for trust, conversion, and repeat bookings'
    ],
    tags: ['Next.js 16', 'React 19', 'TypeScript', 'Tailwind CSS', 'Supabase', 'Resend', 'Twilio'],
    demo: 'https://nova-salon-six.vercel.app/',
    github: 'https://github.com/Azynar/nova-salon',
    image: '/nova-salon.png',
  },
  {
    slug: 'personal-portfolio',
    title: 'Personal Developer Portfolio & Lead Engine',
    category: 'Full-Stack Web',
    status: 'Live',
    featured: false,
    desc: 'High-speed personal brand and client acquisition system built with Next.js App Router, automated Resend email routing, and sub-second performance.',
    long: `A production-grade developer portfolio engineered not just as a résumé, but as an interactive client acquisition engine. Features server-side rendered routes, seamless light/dark mode theming without layout shift (FOUC), secure API contact validation with rate-limiting, and an automated continuous deployment pipeline via Vercel.`,
    problem: 'Standard developer portfolios often look generic, lack clear value propositions for founders, and suffer from sluggish page transitions and poor SEO.',
    solution: 'Engineered a tailored, high-converting Next.js application featuring atomic UI components, responsive typography, JSON-LD Schema.org structured data, and direct multi-channel conversion paths (WhatsApp & Email).',
    outcomes: [
      '100% Lighthouse Best Practices Score',
      'Automated SMTP Delivery via Resend API',
      'Instant Zero-FOUC Theme Switcher',
      'Continuous Deployment CI/CD in < 60s'
    ],
    tags: ['Next.js 16', 'React 19', 'Tailwind CSS', 'Framer Motion', 'Resend API'],
    title: 'Personal Developer Portfolio',
    category: 'Web Development',
    status: null,
    desc: 'A fully deployed developer portfolio with a working contact form, automated emails, and CI/CD straight from GitHub to a live URL.',
    long: `Built and deployed a full-stack portfolio with a working contact form backend, automated email delivery via Resend, and a CI/CD pipeline through GitHub and Vercel. Every push to GitHub redeploys automatically — from a saved file to a live URL in under 60 seconds, no manual steps in between.`,
    problem: 'Needed a compact, fast personal site to showcase work and make contacting easy.',
    solution: 'Built a Next.js app with modular components, an easy contact form, and fast static rendering for pages.',
    tags: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
    demo: 'https://azynardev.vercel.app',
    github: 'https://github.com/Azynar/my-portfolio',
    image: '/portfolio.png',
  },
  {
    slug: 'naija-memecoin',
    title: '$NAIJA Web3 Community Platform',
    category: 'Web3 & Frontend',
    status: 'Live',
    featured: false,
    desc: 'A high-converting Web3 onboarding landing page designed and launched in under a week to introduce decentralized tokens to a regional audience.',
    long: `A specialized frontend build created to onboard non-technical crypto newcomers into a community token ecosystem. Incorporates cultural design cues, interactive tokenomics visualizers, step-by-step wallet connection tutorials, and responsive mobile-first views.`,
    problem: 'Standard cryptocurrency portals are filled with confusing financial jargon and complex interfaces that intimidate first-time users.',
    solution: 'Designed an approachable, educational onboarding flow with clear token distribution infographics, FAQ accordions, and frictionless community links.',
    outcomes: [
      'Designed & shipped in under 7 days',
      'Mobile-first responsive UX (< 1.2s FCP)',
      'Simplified onboarding for 500+ members',
      'Culturally tailored branding & illustrations'
    ],
    tags: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion', 'Web3 UI'],
    title: '$NAIJA Memecoin Landing Page',
    category: 'Web3',
    status: null,
    desc: 'A culturally grounded Web3 landing page for a Nigerian memecoin community, designed and shipped in under a week.',
    long: `A landing page built to introduce and onboard users to a memecoin project with culturally familiar design cues, a clear tokenomics overview, and a low-friction signup flow — built specifically to make Web3 feel approachable to a regional audience unfamiliar with typical crypto-site conventions.`,
    problem: 'Make Web3 approachable for a regional audience.',
    solution: 'Styled copy, clear CTAs and educational sections to lower friction for newcomers.',
    tags: ['React', 'Vite', 'Tailwind CSS', 'Framer Motion'],
    demo: 'https://azynar.github.io/naija-memecoin/',
    github: 'https://github.com/Azynar/naija-memecoin/',
    image: '/naija-memecoin.png',
  },
  {
    slug: 'gigsignal-bot',
    title: 'gigSignal Real-Time Opportunity Bot',
    category: 'Automation & APIs',
    status: 'Case Study',
    featured: false,
    desc: 'Autonomous background daemon that monitors Web3 token listings, DEX liquidity events, and developer bounties—broadcasting instant Telegram alerts.',
    long: `An autonomous Node.js service engineered to poll decentralized exchange logs, smart contract event emitters, and job platforms in real time. It filters out noise using configurable threshold heuristics and immediately broadcasts high-priority opportunities to subscriber channels with markdown-formatted actions.`,
    problem: 'Opportunities in fast-moving Web3 ecosystems are missed when developers and traders must manually check dozens of feeds and dashboards.',
    solution: 'Built a lightweight event-driven Node.js background pipeline with exponential backoff retry mechanisms, Telegram Bot API integration, and webhook dispatching.',
    outcomes: [
      'Eliminated 15+ hours/week of manual feed tracking',
      '< 3 second latency from on-chain event to Telegram ping',
      'Configurable signal filter heuristics',
      'Fault-tolerant retry and healthcheck logic'
    ],
    tags: ['Node.js', 'Telegram API', 'REST Webhooks', 'Event Emitters', 'Railway'],
    title: 'gigSignal Automation Bot',
    category: 'Automation',
    status: 'Inactive',
    desc: 'An automation bot that tracked Web3 opportunities in real time and pushed instant alerts to Telegram — currently inactive after hitting free-tier hosting limits.',
    long: `A small service that watched multiple Web3 data feeds — token launches, DEX listings, bounties, and job postings — and broadcast curated signals to subscribers via Telegram, saving hours of manual checking every week. Built to be lightweight and reliable, with retry logic and basic monitoring. Currently paused after exceeding free-tier hosting limits — screenshots below show it running live`,
    problem: 'Users miss important real-time signals across many channels.',
    solution: 'Create a single bot that centralizes signals and delivers them to interested users.',
    tags: ['Node.js', 'Telegram API', 'Railway'],
    demo: 'N/A',
    github: 'https://github.com/Azynar/gigSignal_bot',
    image: '/gigsignal-bot.png',
  },
];

export function getProjectBySlug(slug) {
  return projects.find((p) => p.slug === slug) || null;
}

export default projects;